auto: true

markdown: rdiscount
pygments: true
paginate: 6
permalink: /:title

title: blosoom.github.com
url: http://blosoom.github.com
feed: /atom.xml
author:
    name: Blosoom
description: "Blosoom\'s Blog"
author_info: <a href="http://blosoom.github.com/about">Blosoom</a>
